import React from 'react';
import { Button } from '@/components/ui/button';
import { X } from 'lucide-react';
import { getClientInfluencerInfo } from '@/lib/clientConfig';

interface ChatDisclaimerModalProps {
  isOpen: boolean;
  onContinue: () => void;
  onClose: () => void;
}

const ChatDisclaimerModal = ({ isOpen, onContinue, onClose }: ChatDisclaimerModalProps) => {
  const influencer = getClientInfluencerInfo();

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-900 rounded-2xl max-w-md w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">
            Disclaimer
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-full transition-colors"
          >
            <X className="h-5 w-5 text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4">
          <div className="text-gray-700 dark:text-gray-300 leading-relaxed">
            <p className="mb-4">
              This AI Persona is a simulated digital experience and does not represent real-time communications with <strong>{influencer.displayName}</strong>. All responses are generated by artificial intelligence for entertainment purposes only.
            </p>
            
            <p className="mb-4">
              The AI Persona may generate responses on a wide range of topics. These responses are not medical, legal, financial, or professional advice and should not be relied upon as such. Always seek qualified professional advice for personal matters.
            </p>
            
            <p className="font-medium">
              By continuing, you acknowledge that you understand and agree to these terms.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="flex gap-3 p-6 border-t border-gray-200 dark:border-gray-700">
          <Button
            variant="outline"
            onClick={onClose}
            className="flex-1"
          >
            Cancel
          </Button>
          <Button
            onClick={onContinue}
            className="flex-1 bg-red-500 hover:bg-red-600 text-white"
          >
            Continue
          </Button>
        </div>
      </div>
    </div>
  );
};

export default ChatDisclaimerModal;
